export const FONT_SIZE = 14;
export const GRAPH_HEIGHT = 250;
export const GRAPH_WIDTH = 250;
export const FONT_COLOR = "#ffe0fd";
export const BAR_HOVER_BACKGROUND_COLOR = "rgba(245, 89, 255, 0.5)";
export const BAR_HOVER_BORDER_COLOR = "rgba(245, 89, 255, 1)";
export const HTTP_BACKGROUND_COLOR = "#d851ab";
export const PERSISTENCE_BACKGROUND_COLOR = "#bc75d0";
export const MEMORY_BACKGROUND_COLOR = "#a566e0";